/**
 * Agent → UI event bus.
 *
 * Lets the agent loop in `agent.ts` emit lifecycle events that the Ink UI
 * (or any other renderer) subscribes to.
 *
 * Phase 13: Ink mode is the default — the agent's existing `console.log` /
 * `console.warn` / `console.error` calls are monkey-patched at Ink mount
 * time (`redirectConsoleToInk()` below) so they fan out as `log` events
 * automatically. Code added since Phase 12 emits structured events
 * directly (`tool_start`, `chunk_plan`, `assistant_message`, etc.); the
 * console redirect is the bridge that keeps the older callsites usable
 * without rewriting them. Opt out of Ink with `--legacy`, `SYS_LEGACY=1`,
 * or `SYS_INK=0`.
 */

import { EventEmitter } from "node:events"

export type LogLevel = "info" | "muted" | "success" | "warning" | "error" | "accent"

export type AgentEvent =
  | { type: "clear" }
  | { type: "log"; level: LogLevel; text: string }
  | { type: "spinner"; text: string }
  | { type: "spinner_stop" }
  | { type: "complete" }
  // ── Phase 12 Stage 4: structured tool-call lifecycle events ──
  // The agent emits `tool_start` when it dispatches a tool call and
  // `tool_end` when the tool resolves. The Ink AgentStream renders one
  // <ToolCard> per id; the card's visual state follows the lifecycle
  // (running → success | error).
  //
  // `id` correlates start ↔ end. Generated by the agent (per-run
  // counter) and treated as opaque by the renderer.
  // `label` is the human-readable formatToolLabel output, computed at
  // start time so the card has the right title before the tool resolves.
  | { type: "tool_start"; id: string; tool: string; label: string; args?: Record<string, unknown> }
  | { type: "tool_end"; id: string; ok: boolean; error?: string }
  // ── Phase 12 Stage 5: Header zone state events ──
  // The agent emits these whenever the server response carries fresh
  // awareness or chunk-plan data. The Ink Header reads them via the
  // useAgentEvents reducer to drive the colour-lerped awareness badge
  // and the chunk-pulse cell.
  //
  // `awareness_update` mirrors the server's awarenessSnapshot payload
  // (Phase 11 Stage 5). `lastSignal` is the most recent divergence
  // signal text or null when nothing has fired this run.
  | { type: "awareness_update"; state: "on_track" | "off_course" | "blocked"; confidence: number; lastSignal?: string | null }
  // `chunk_plan` fires once per chunk planner brief — the chunkIndex
  // monotonically increases. `nextAction` is the planner's one-line
  // intent. `fileCount` is the number of files the chunk will touch.
  | { type: "chunk_plan"; chunkIndex: number; nextAction: string; fileCount?: number }
  // ── Phase 12 Stage 6: assistant message stream ──
  // The agent emits `assistant_message` when a completion / summary
  // text arrives from the model. The Ink AgentStream renders the most
  // recent one via <Typewriter> so the user sees the text type out
  // instead of appearing instantly — feels like writing, not loading.
  // Cleared by `clear` when a new prompt arrives.
  | { type: "assistant_message"; text: string }

const emitter = new EventEmitter()
emitter.setMaxListeners(20)

const CHANNEL = "event"

export function emitAgent(event: AgentEvent): void {
  emitter.emit(CHANNEL, event)
}

export function onAgent(handler: (event: AgentEvent) => void): () => void {
  emitter.on(CHANNEL, handler)
  return () => emitter.off(CHANNEL, handler)
}

/** True when the runtime should emit events instead of writing to the console.
 *  Phase 13: Ink mode is the default. Opt out with SYS_LEGACY=1, SYS_INK=0,
 *  or `--legacy` (the index.ts entrypoint sets SYS_INK=0 when it sees that
 *  flag, so we only need to read the env here). */
export function isInkActive(): boolean {
  if (process.env.SYS_INK === "0") return false
  if (process.env.SYS_LEGACY === "1") return false
  return true
}

/**
 * Phase 14 Stage 1: predicate every legacy-only renderer should gate on.
 * Returns the inverse of `isInkActive()` — single canonical name so future
 * contributors don't re-derive the check at each callsite.
 *
 * Use it to wrap any `console.log` that prints heavy ASCII chrome
 * (boxTop / boxMid / boxBot SUMMARY boxes, renderPipelineBox, MEMORY
 * blocks), any raw cursor-move writes (`process.stdout.write("\x1b[nA")`),
 * or any other inline rendering whose Ink-mode equivalent is already
 * emitted as a structured event. In Ink mode the redirected console.log
 * would route those bytes through the bus too, producing double-rendered
 * content (and in the case of cursor moves, a corrupted Ink layout).
 */
export function shouldRenderInlineForLegacy(): boolean {
  return !isInkActive()
}

/**
 * Redirect raw `console.log` / `console.warn` / `console.error` calls
 * through the agent event bus so they render inside `<AgentStream>` as
 * `log` entries instead of writing directly to stdout (where they would
 * stomp over Ink's render zone).
 *
 * Phase 12 built the alive UI components but the agent's existing 100+
 * `console.log` callsites in agent.ts / executor.ts / cli/render.ts
 * still wrote directly to stdout. In Ink mode that produced visual
 * chaos — Ink-rendered cards + Header + StatusLine fighting with raw
 * print lines. This bridge fixes it without touching every callsite:
 * we monkey-patch the three console methods on Ink mount and route
 * each call into the bus as a `log` event with the matching level.
 *
 * Restored on Ink unmount via `restoreConsole()` so anything that runs
 * after the UI exits (e.g. error handler, telemetry flush) prints
 * normally.
 */
let originalConsole: { log: typeof console.log; warn: typeof console.warn; error: typeof console.error } | null = null

export function redirectConsoleToInk(): void {
  if (originalConsole) return // idempotent
  originalConsole = {
    log: console.log.bind(console),
    warn: console.warn.bind(console),
    error: console.error.bind(console),
  }
  console.log = (...args: unknown[]) => emitAgent({ type: "log", level: "info", text: formatConsoleArgs(args) })
  console.warn = (...args: unknown[]) => emitAgent({ type: "log", level: "warning", text: formatConsoleArgs(args) })
  console.error = (...args: unknown[]) => emitAgent({ type: "log", level: "error", text: formatConsoleArgs(args) })
}

export function restoreConsole(): void {
  if (!originalConsole) return
  console.log = originalConsole.log
  console.warn = originalConsole.warn
  console.error = originalConsole.error
  originalConsole = null
}

/** Stringify console args the way the standard logger does, then strip
 *  ANSI escapes so Ink renders the text cleanly. The level argument to
 *  `<Text color>` in AgentStream paints the whole entry — inline ANSI
 *  inside the string would just clutter the output. */
function formatConsoleArgs(args: unknown[]): string {
  const joined = args
    .map((a) => {
      if (typeof a === "string") return a
      if (a instanceof Error) return a.stack ?? a.message
      try { return JSON.stringify(a) } catch { return String(a) }
    })
    .join(" ")
  return stripAnsi(joined)
}

const ANSI_RE = /\x1b\[[0-9;]*[A-Za-z]/g
function stripAnsi(s: string): string {
  return s.replace(ANSI_RE, "")
}
